### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by ftoledo** [javadmohebbi/asterisk-java-operator-panel#1]
ragnarok@ragnarok:/tmp$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

ragnarok@ragnarok:/tmp$ java -jar ajop-v1.jar 
ene 15, 2020 8:43:22 PM org.asteriskjava.manager.internal.ManagerConnectionImpl connect
INFORMACIÓN: Connecting to 192.168.1.25:5038
ene 15, 2020 8:43:22 PM org.asteriskjava.manager.internal.ManagerConnectionImpl setProtocolIdentifier
INFORMACIÓN: Connected via Asterisk Call Manager/1.3
ene 15, 2020 8:43:22 PM org.asteriskjava.manager.internal.ManagerConnectionImpl doLogin
INFORMACIÓN: Successfully logged in
ene 15, 2020 8:43:23 PM org.asteriskjava.manager.internal.ManagerConnectionImpl doLogin
INFORMACIÓN: Determined Asterisk version: Asterisk 11
Exception in thread "AWT-EventQueue-1" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.remove(ArrayList.java:496)
	at org.ajop.manage.Dahdi.getCommandDahdiShowChannels(Dahdi.java:45)
	at org.ajop.gui.SettingForm.initContents(SettingForm.java:192)
	at org.ajop.gui.SettingForm.access$16(SettingForm.java:161)
	at org.ajop.gui.SettingForm$1.run(SettingForm.java:115)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by javadmohebbi** [comment]
Hi @ftoledo, This repo is not maintained any more. Moreover, In newer versions of Asterisk this JAVA application might not work

**Comment by ftoledo** [comment]
hi @javadmohebbi 
Do you known another free panel to recommend?

thanks!

**Comment by javadmohebbi** [comment]
> hi @javadmohebbi
> Do you known another free panel to recommend?
> 
> thanks!

You can use Flash Operator Panel. [FOP2 Website](https://www.fop2.com/)
